# node-server deployment test yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-deployment
spec:
  replicas: 4
  strategy: # 滚动更新策略
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 # 最小不可用的服务数
  selector:
    matchLabels:
      app: node-server-pod
  template:
    metadata:
      labels:
        app: node-server-pod
    spec:
      containers:
        - image: wuyupei/node-server:v11.0.0
          name: node-server-container
          livenessProbe: #存活探针
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe: #就绪探针
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            successThreshold: 1
