# node-server deployment test yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-server-pod
  template:
    metadata:
      labels:
        app: node-server-pod
    spec:
      containers:
        - image: wuyupei/node-server:v8.0.0
          name: node-server-container
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
